"""password commit

Revision ID: 227b30c56be7
Revises: 7b637eb92e0d
Create Date: 2022-05-10 14:52:32.856815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227b30c56be7'
down_revision = '7b637eb92e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
