"""posts_id Migration

Revision ID: 98ebf6bd5ce9
Revises: a9515553bcc4
Create Date: 2022-05-13 18:10:17.476922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ebf6bd5ce9'
down_revision = 'a9515553bcc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.add_column('downvotes', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'downvotes', 'posts', ['post_id'], ['id'])
    op.add_column('upvotes', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'upvotes', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_column('upvotes', 'post_id')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    op.drop_column('downvotes', 'post_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
