"""upvote Migration

Revision ID: a9515553bcc4
Revises: f6243af9e944
Create Date: 2022-05-13 17:49:34.430164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9515553bcc4'
down_revision = 'f6243af9e944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'downvotes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'upvotes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upvotes', type_='foreignkey')
    op.drop_constraint(None, 'downvotes', type_='foreignkey')
    # ### end Alembic commands ###
