"""post Migration

Revision ID: b54af9f718e8
Revises: 227b30c56be7
Create Date: 2022-05-10 23:46:39.155795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54af9f718e8'
down_revision = '227b30c56be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Posts', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    op.drop_constraint(None, 'Posts', type_='foreignkey')
    op.drop_column('Posts', 'user_id')
    # ### end Alembic commands ###
